### ISSUE TITLE
Vereinfachung des Namensformats

### ISSUE THREAD

**Issue by moewew** [Ekkehardt/biblatex-iest#2]
Man kann die Definition des eigenen Namensformates `tubafshort` umgehen, indem man `firstinits=true` setzt und `\DeclareNameAlias{default}{last-first}` deklariert.

Ein eigenes Namensformat ist dann nicht mehr notwendig, dadurch wird der Stil etwas flexibler und noch kürzer.

Durch `firstinits=true` wird weiterhin gewährleistet, dass die Namen tatsächlich durchgängig und in allen Fällen nur mit Initialen angeben werden, mit jetzigen Format ist das z.B. bei Herausgebern in `@inbook`s nicht der Fall.

**Comment by Ekkehardt** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

Hallo,

sowohl das:

Am 11.08.2015 um 15:09 schrieb moewew:
> Man kann die Definition des eigenen Namnesformates |tubafshort|
> umgehen, indem man |firstinits=true| setzt und 
> |\DeclareNameAlias{default}{last-first}| deklariert.
> 
> Ein eigenes Namensformat ist dann nicht mehr notwendig, dadurch
> wird der Stil etwas flexibler und noch kürzer.

als auch das in Issue #1 angemerkte sind gute Verbesserungsvorschläge,
vielen Dank. Ich setzte beide am Wochenende um, wenn ich meine
Diplomarbeit los bin. Oder kurz davor ;)

Mit freundlichen Grüßen
E. Frank Sandig
Freiberg

- --
Lubuntu 14.04
TeX Live 2015
Texstudio 2.6.6

- --
PGP-Fingerprint: 2B8B 97E9 40F0 3DCA 953D 33CB 6498 E646 9D01 A91F
Key 0x9D01A91F unter http://sandig-fg.de/gpg-key.asc
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2.0.22 (GNU/Linux)

iF4EAREIAAYFAlXJ/m4ACgkQZJjmRp0BqR+wCAD7BsRCjf9Maqj9gPyXYFO6fN6N
96JJc1Q4rNKZUGxGHo4BAKsvJsHmHvbKb0RyRL2qJE+zy1TeifB4WvaZvXjhCRWr
=nF3s
-----END PGP SIGNATURE-----

**Comment by Ekkehardt** [comment]
So, kompilierzeit sinnvoll genutzt ;)

**Comment by moewew** [comment]
Man kann die Option `firstinits=true` auch in der `.bbx`-Datei direkt setzen, sodass an mit der Nutzung des Stils `iets` schon automatisch `firstinits=true` aktiviert.
Auch die Sortierung lässt sich so einstellen.

Es böte sich also an

    ExecuteBibliographyOptions{firstinits=true,sorting=none}

noch in die `.bbx`-Datei aufzunehmen.

**Comment by Ekkehardt** [comment]
Ich kannte die Möglichkeit, habe sie aber nicht genutzt. Jetzt ist das ganze sauberer, vielen Dank. Zusätzlich habe ich noch den Flattersatz in der Bibliografie aufgenommen, der war zwar nicht streng vorgegeben, ist am IEST aber üblich.

**Comment by moewew** [comment]
Die Änderungen in Version 3.3 haben hier ja auch schon Beachtung gefunden. Du darfst aber nicht vergessen, dass in Version vor 3.3 `giveninits` nicht bekannt ist. Ich bin mir nicht ganz sicher, was hier die beste Vorgehensweise ist. Da `firstinits` zur Zeit noch funktiniert und nur eine Warnung ausgibt, könnte man darüber nachdenken, diese alte Option noch für einige Zeit zu nutzen und dann erst umzusteigen. Oder man versucht, die biblatex-Version herauszufinden und passt den Aufruf daran an. (Da habe ich zur Zeit aber keine gute Erkennungsmethode im Kopf.)

Ähnliches gilt auch für
```
\DeclareNameAlias{default}{last-first} 
```
das im neuen Format
```
\DeclareNameAlias{default}{family-given} 
```
heißen sollte.

**Comment by moewew** [comment]
`\@ifpackagelater` scheint eine gute Idee zu sein, siehe [Load different options depending on package version](http://tex.stackexchange.com/q/82395/35864).

Bei Dir würde das wohl
```
\ExecuteBibliographyOptions{sorting=none,block=ragged}

\@ifpackagelater{biblatex}{2016/03/03} % teste auf neues Namenformatsystem in biblatex
  {\ExecuteBibliographyOptions{giveninits=true}%
   \DeclareNameAlias{default}{family-given}}
  {\ExecuteBibliographyOptions{firstinits=true}%
   \DeclareNameAlias{default}{last-first}}
```
bedeuten.
